In [ ]:
import numpy as np


In [ ]:
gridWorld=np.zeros((2,5,5), dtype=int)

lake=(0,0)
fire=[(4,4)]
smoke=[(1,2),(3,2)]
boulders=[(3,4),(2,4)]

print(gridWorld)


[[[   0    0    0    0    0]
  [   0    0    0    0    0]
  [   0    0    0    0 -100]
  [   0    0    0    0 -100]
  [   0    0    0    0    0]]

 [[   0    0    0    0    0]
  [   0    0    0    0    0]
  [   0    0    0    0 -100]
  [   0    0    0    0 -100]
  [   0    0    0    0    0]]]


In [ ]:
def terminal(state):
    if tuple(state[1:2]) in fire and state[0]:
        return True
    elif tuple(state[1:2]) in boulders:
        return True 
    else:
        return False
    
def reward(state):
    pos = tuple(state[1:2])
    if pos in fire and state[0]:
        return 100
    elif pos in smoke:
        return -10
    elif pos in boulders:
        return -100
    else:
        return -1

def movement(state, dirc):
    if dirc=='N':
        if tuple(state[1:2])==(0,1) and not state[0]:
            return (1, 0,0)
        return state if state[2] == 4 else (state[0], state[1], state[2]-1)
    
    elif dirc=='S':
        return state if state[2] == 0 else (state[0], state[1], state[2]+1)
    
    elif dirc=='E':
        return state if state[1] == 4 else (state[0], state[1]+1, state[2])
    
    elif dirc=='W':
        if tuple(state[1:2])==(1,0) and not state[0]:
            return (1, 0,0)
        return state if state[1] == 0 else (state[0], state[1]-1, state[2])
    
    else:
        return state
    
def possible_states(state,dirc):
    if dirc == 'N':
        return [movement(state, 'N'), movement(state, 'E'), movement(state, 'W'),movement(state, '#')]
    elif dirc == 'S':
        return [movement(state, 'S'), movement(state, 'E'), movement(state, 'W'),movement(state, '#')]
    elif dirc == 'E':
        return [movement(state, 'E'), movement(state, 'N'), movement(state, 'S'),movement(state, '#')]
    elif dirc == 'W':
        return [movement(state, 'W'), movement(state, 'N'), movement(state, 'S'),movement(state, '#')]
    

In [ ]:
LOWER_BOUND=-1000
def value_func( state, gamma):
    value=LOWER_BOUND
    print(gridWorld)
    if tuple(state[1:2]) in smoke:
        for dirc in ['N','S','E','W']:
            p_states = possible_states(state, dirc)
            value += 0.4 * (reward(p_states[0]) + gamma * gridWorld[p_states[0][0], p_states[0][1], p_states[0][2]])
            value += 0.4 * (reward(p_states[3]) + gamma * gridWorld[p_states[3][0], p_states[3][1], p_states[3][2]])
            for i in range(1,3):
                p_state = p_states[i]
                value += 0.1 * (reward(p_state) + gamma * gridWorld[p_state[0], p_state[1], p_state[2]])
            value = max(value, LOWER_BOUND)
                    
    else:
        for dirc in ['N','S','E','W']:
            p_states = possible_states(state, dirc)
            value += 0.7 * (reward(p_states[0]) + gamma * gridWorld[p_states[0][0], p_states[0][1], p_states[0][2]])
            for i in range(1,4):
                p_state = p_states[i]
                value += 0.1 * (reward(p_state) + gamma * gridWorld[p_state[0], p_state[1], p_state[2]])
            value = max(value, LOWER_BOUND)
        
    return value


[[[   0    0    0    0    0]
  [   0    0    0    0    0]
  [   0    0    0    0 -100]
  [   0    0    0    0 -100]
  [   0    0    0    0    0]]

 [[   0    0    0    0    0]
  [   0    0    0    0    0]
  [   0    0    0    0 -100]
  [   0    0    0    0 -100]
  [   0    0    0    0    0]]]


np.float64(-4.0)